language: node_js
node_js:
  - "10"
  - stable
  - lts/*
cache: yarn
script:
  - yarn run test
jobs:
  include:
    - stage: Produce Coverage
      node_js: stable
      script: jest --collectCoverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
